### ISSUE TITLE
A chance to collaborate?

### ISSUE THREAD

**Issue by naikymen** [DerAndere1/contact_DerAndere1#7]
Hi! I just found your project. The work you've done looks **awesome**.

A couple friends and I have been working on very similar stuff, and also posted in the OT repo a while ago: https://github.com/Opentrons/opentrons/issues/11542

I was hoping there is a chance for us to collaborate. Please let me know if you want to have a chat :)

You can find me as naikymen at [the GOSH forum](https://forum.openhardware.science/u/naikymen/), [the PLR forum](https://forums.pylabrobot.org/u/naikymen/), and elsewhere.

Cheers!

**Comment by DerAndere1** [comment]
Thanks for the interest. It is great to hear that others have the same urge to move open hardware/software/research forward. I cannot guarantee to regularly find time to continue the discussion due to a new job. 

I read that you plan to integrate one of the existing frameworks (opentrons or PyLabRobot). I think that this is a very good decision. Otherwise, I like your software design (seperate GUI and backend "protocol2gcode". That is similar to my design of GGCGen and its backend pyotronext. 

Let me briefly explain how I achieved compatibility with opentrons: Most of the files of the pyotronext source code are just bloat to mimic opentrons code structure. For me with my limited coding skills this was the simplest solution to become opentrons APIv2 compatible. 

At the time I wrote pyotronext, the parts in original opentrons code that dealt with g-code sending were difficult to isolate and adapt to other hardware. So in pyotronext, generation of g-code strings and serial communication is reimplemented in files virtualLab.py and serialCommunication.py, based on [mecode](https://github.com/jminardi/mecode).

**Comment by naikymen** [comment]
Hello DerAndere, thanks for the quick reply!

> "I cannot guarantee to regularly find time to continue the discussion due to a new job."

That's alright. I would have liked to come across your work a couple years back, but any form of collaboration would be great.

If you want to join the discussions I can let you know when one comes up. I'll probably have a meeting with the PyLabRobot folks next week, for example.

> "That is similar to my design of GGCGen and its backend pyotronext."

Yes!

Though I would have liked to re-use 3D printers directly, which are just about everywhere. In retrospect, building a custom CNC frame is quite a lot to ask.

> "Most of the files of the pyotronext source code are just bloat to mimic opentrons code structure."

I was about to do _exactly_ the same as you did. I hit a wall with the OT repo, and just now the PyLabRobot folks told me that it is actually more complex than necessary.

I'm still interested in knowing if OT's Protocol Designer can be bridged to other projects. I understand that it outputs JSON, which must then be converted to OT python code somewhere.

Were you able to learn about how that works?

> "based on [mecode](https://github.com/jminardi/mecode)."

That is _so_ nice.

**Comment by naikymen** [comment]
PS: from a quick read of your repos, I understand that you developed a multi-axis Marlin firmware. I started moving towards [Klipper](https://www.klipper3d.org/) because it supports controlling many MCUs in synchrony, through a single entry point for GCODE. The downside is that it is limited to only 3 axes[^1]. I'd like to know your take on this aspect.


[^1]: 3 axes + extruders. However Klipper extruders cannot be homed, and this is needed for micropipettes. On the other hand extra steppers in Klipper cannot be synchronized to the main 3 axes (i.e. they are not proper _axes_).

**Comment by DerAndere1** [comment]
Initially, I repurposed the extruder stepper as the stepper that moves the pipette piston. Later I added enstops and homing to the "E-Axis": https://github.com/DerAndere1/Marlin/tree/2.0.x_E_homing . This allowed some interesting setups in combination with Marlin's MIXING_EXTRUDER feature. It was a quick but unconventional hack that would have to be implemented in each firmware I wanted to support with pyotronext. I came to the conclusion that it is better to use more conventional G-code (instead of the "E-axis" use conventional extra axes). I regard LinuxCNC (the successor of NIST RS274NGC Interpreter, Version 3) as the reference. Their G-code uses Axis names XYZUVWABC. That was the first reason for adding extra axes to Marlin. The second reason was that the addition of extra exes had the added benefit of allowing Marlin to be used more generally as firmware for multi-axis CNC machines (mills, 3D-printers, cutters, articulated robots). I never had the actual need for a liquid handling station. The programming itself was my hobby, so I had no time constraints and could choose the harder, more time consuming but more complete solution.

**Comment by naikymen** [comment]
Indeed the complete solution would be ideal. I will re-consider the Marlin/RAMPS combo if modding Klipper doesn't work out.

Also, I'll probably come back with questions about reusing pyotronext. Moving to PyLabRobot is nice, but being able to bridge OT's protocol library to any suitable robot would be _awesome_. Right?

Cheers! and thanks :)

**Comment by naikymen** [comment]
![image](https://user-images.githubusercontent.com/3259326/224606698-4e4e1906-cadd-43c0-a40e-a4f8140bb714.png)

Hi again!

After lots of frustration, I managed to get 6-axes on Klipper, and other CNC stuff I needed.

I have also forked pyotronext, which after a few minor fixes works for generating GCODE from OT scripts.

I wanted to share progress, close this, and to thank you for the work.

Best!

**Comment by DerAndere1** [comment]
I gave you a github star for your klipper fork. Congrats for the awesome work. I too had so much frustration when I worked on extending Marlin!!! You may want to think about opening a PR to bring your multi-axis extension to the main klipper repo. Or at least inform the klipper community and point them to your code so they can decide if they want to bring it to klipper. Regarding the OT repo, yeah that IS complex. But they are working on removing redundant stuff. I am looking forward to see how you proceed. All the best
